### ISSUE TITLE
Alternative Scanners, not plugins

### ISSUE THREAD

**Issue by UncleBOBa** [ukdtom/PMSLibShare#1]
Hi and thanks a lot for your work! I use the additinal scanner like this one https://forums.plex.tv/discussion/107736/new-series-scanner-with-bdmv-disc-image-support
It will be so helpful, if you will add to PLEX-Share one more resource (Scanners folder) to easy put Python files for additional Scanners.

**Comment by ukdtom** [comment]
Custom scanners should be put in a directory named scanners at the root of the share this tool creates for you.

The directory doesn't exists by default though

**Comment by UncleBOBa** [comment]
There can be different scanners. For movies, for series. Put it together in
one folder?

3 мар. 2017 г. 15:01 пользователь "Tommy Mikkelsen" <
notifications@github.com> написал:

**Comment by ukdtom** [comment]
Create a folder named scanners

Put each scanner in it's own bundle dir below that

**Comment by UncleBOBa** [comment]
And the names of subdirs? Movie and Series?
Thanks, will try!

3 мар. 2017 г. 16:37 пользователь "Tommy Mikkelsen" <
notifications@github.com> написал:

**Comment by ukdtom** [comment]
Subdir name should be NameOfScanner.bundle
