### ISSUE TITLE
Undo changes?

### ISSUE THREAD

**Issue by Eulogium** [ukdtom/PMSLibShare#2]
Hi, thank you so much for creating PMSLibShare. It saved me a lot of trouble of having to use putty to find the Plex directory on my Qnap. I noticed that now all the directories are listed by their full path in the Plex GUI. Is there any way to undo the changes that PMSLibShare made?

**Comment by ukdtom** [comment]
I have no idea about what you mean?

**Comment by Eulogium** [comment]
I apologize for not being clear. In Plex, while doing things such as adding a folder to a library, the paths were simple (i.e. \Music). Now, after installing PMSLibShare, the paths are exact (i.e. /share/CACHEDEV2_DATA/Music). Installing PMSLibshare revealed the Plex Media Server folder, which is what I wanted, but it also revealed the full paths of all folders, which is excessive information. I no longer need to see the Plex Media Server folder, but even after uninstalling/removing PMSLibshare, the paths stay exact.

Please forgive me for not being more savvy with this sort of thing. It seems like there is a toggle or a function that was dumbing down the complexity, like hiding the full names of the paths.  I just replaced my TS-251+ with a new TVS-682. When I initially set up my TS-251+ I followed a guide for installing Plex that had me manually create the Plex Media Server folder among a few other things that I can't remember, but the display of the directories looked like "/share/CACHEDEV2_DATA/" so I thought that was the norm until my new TVS-682 had everything displayed in a much simpler layout.

**Comment by ukdtom** [comment]
PMSLibShare only set it's own path, and has absolutely nothing to do with other shares etc.

My guess, a firmware upgrade of QTS caused a change

**Comment by Eulogium** [comment]
It was not a QTS update, this was a direct before and after change when I installed PMSLibShare. The issue is entirely within Plex, so maybe the switch from simple to full paths has something to do with Plex hiding its server folder. Either way, it's not something I can't live with, I was just wondering if there was a way to bring it back to its default state.

**Comment by ukdtom** [comment]
Sorry, but 100% unrelated to PMSLibShare!

All it does, is this:
`addshare Plex "$SHARE_DIR" -uw:admin`

And above means add a share named Plex pointing to the library directory, and allow admin user only

You can see the code here:
https://github.com/ukdtom/PMSLibShare/blob/master/PMSLibShare/shared/PMSLibShare.sh


But when said, could your issue maybe be related to:

http://forums.plex.tv/discussion/287902/special-announcement-qnap-codexpack-4-5-0-issues-with-pm
